4th time warning ignore

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -25,10 +25,17 @@ jobs:
       - name: Build React app
         env:
           CI: true
-        run: npm run build
+        run: |
+          npm run build --if-present
+          if [ $? -ne 0 ]; then
+            echo "::set-env name=BUILD_STATUS::failure"
+          else
+            echo "::set-env name=BUILD_STATUS::success"
+          fi
         working-directory: street-light
 
       - name: Deploy to cPanel
+        if: env.BUILD_STATUS == 'success'
         uses: SamKirkland/FTP-Deploy-Action@4.0.0
         with:
           server: ${{ secrets.FTP_SERVER }}
